# Global configuration

format = """
$directory$git_branch$git_status$python
$character
"""

[character]
error_symbol = '[▶](bold red)'
success_symbol = '[▶](bold green)'
vimcmd_replace_one_symbol = '[](bold purple)'
vimcmd_replace_symbol = '[](bold blue)'
vimcmd_symbol = '[](bold cyan)'
vimcmd_visual_symbol = '[](bold yellow)'

[directory]
format = "[$path]($style)( [$read_only]($read_only_style))"
home_symbol = "~"
read_only = ""
truncation_symbol = ".../"

[git_branch]
format = "( [$branch(:$remote_branch)]($style))"
style = "#8087A4"

[git_status]
format = "( [$all_status]($style))"
modified = "󱈸"

[python]
format = "( [$symbol ${version}]($style bold) [$virtualenv]($style italic))"
python_binary = "python"
style = "yellow"
symbol = ""
version_format = "$raw"
